### ISSUE TITLE
Cannot use messaging

### ISSUE THREAD

**Issue by nick-verida** [verida/vue-starter-kit#16]
When I try to initialise messaging I get the following error:

```
Uncaught (in promise) SyntaxError: redeclaration of const schema2
    compileSchema index.js:90
    inlineOrCompile index.js:149
    resolveRef index.js:143
    code ref.js:19
```

See the branch https://github.com/verida/vue-starter-kit/tree/bug/cannot-use-messaging to replicate

**Comment by cmcWebCode40** [comment]
@nick-verida, 

I have fixed the issue, it is a small change here's is [commit](https://github.com/verida/vue-starter-kit/commit/60c3fd6b4e229cd9786a25d7a2617c040ba0910d)

**Comment by nick-verida** [comment]
@cmcWebCode40 I still have the same issue after pulling this. 

How did you test it?

![image](https://user-images.githubusercontent.com/87622993/165449446-d551f8bd-f690-4d9b-99e0-2fff97b52fb8.png)

**Comment by cmcWebCode40** [comment]
I clicked on the issue button , then  the `Messaging` object was logged in the console.

**Comment by nick-verida** [comment]
@cmcWebCode40 I've redeployed it from source on AWS and it is getting the same error: https://bug-cannot-use-messaging.d2h6ykwy81i9ka.amplifyapp.com/

Can you please make sure you aren't using locally linked versions of the components or something?

**Comment by cmcWebCode40** [comment]
@nick-verida, 

I have updated the `@verida/vue-account` component to use the latest version(0.1.31), I believe this should fix the issue, but I was unable to test this properly because, 

I tried re-installing the dependencies in package.json but I was getting this error , 
please can you check if you can run `yarn` successfully on the repo from your machine?

```
 vue-starter-kit git:(bug/cannot-use-messaging) ✗ yarn             
yarn install v1.22.17
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
[5/5] 🔨  Building fresh packages...
[1/6] ⠈ leveldown
[-/6] ⠈ waiting...
[3/6] ⠈ fsevents
[6/6] ⠈ node-sass
error /Users/chinweikemichael/Desktop/verida/vue-starter-kit/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /Users/chinweikemichael/Desktop/verida/vue-starter-kit/node_modules/node-sass
Output:
Building: /Users/chinweikemichael/.nvm/versions/node/v14.17.6/bin/node /Users/chinweikemichael/Desktop/verida/vue-starter-kit/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/Users/chinweikemichael/.nvm/versions/node/v14.17.6/bin/node',
gyp verb cli   '/Users/chinweikemichael/Desktop/verida/vue-starter-kit/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]

```

**Comment by nick-verida** [comment]
@cmcWebCode40 make sure you are using the correct version of node. `nvm use` should work

Just by pushing to that branch you trigger a build, so https://bug-cannot-use-messaging.d2h6ykwy81i9ka.amplifyapp.com/ is automatically up to date with this branch.

However, it looks like something else has changed. 

This line executes but nothing else: https://github.com/verida/vue-starter-kit/blob/93bfe5a7900e8386963a4f980cc83b69dc138b84/src/views/Home.vue#L74

It looks like `veridaContex` isn't being set now?

**Comment by cmcWebCode40** [comment]
the been set here 

> It looks like veridaContext isn't being set now?
At first login, it doesn't set properly `veridaContext` remains as null  but when you reload the page the veridaContext sets correctly

let me resolve the yarn install issues then confirms as well .

**Comment by cmcWebCode40** [comment]
@nick-verida, 

I'm still getting the same error ATM, I have installed the correct node version  (14.17.1)
also, run `nvm use 14.17.1`.

This is weird but I'm still trying to know why this error occurs

**Comment by cmcWebCode40** [comment]
@nick-verida,
 
I have been able to refactor the code to use the latest version of the `vue-account` library, and it works now.


The error occurs because the `context` is available in the `$VeridaHelper` module, so retrieving it from the` vda-account` component causes this error 

basically, the `context` it's been retrieved from the vue global module exposed by the plugin(`vue-account`)  
which is the `this.$VeridaHelper.context`. 

I'm  really not sure if  developers will need to utilize the methods in the `VeridaHelpers` in our `vue-account` components, 
that's why the   `$VeridaHelper` was available as a global module. 

but if not we can just allow the `this.$VeridaHelper`  module to be used internally within the  `vue-account` components alone this would prevent the above error.

**Comment by nick-verida** [comment]
This seems to have been caused by the `veridaContext` being a Vue proxy object. 

Doing this seems to fix it:

```
let vCtx = toRaw(this.veridaContext);
const messaging = await vCtx.getMessaging();
```
